### ISSUE TITLE
Updating data-table list causes error

### ISSUE THREAD

**Issue by trentgillham** [PredixDev/px-data-table#29] opened 2016-05-11 15:42 UTC
If I make a request and push new data on the array that is passed into the px-data-table, I get the following error: **aha-table.html:590 Uncaught TypeError: Cannot read property 'row' of undefined**

Trying to find the most efficient way to update the list with new items.

If I delete from the array, the table is updated accordingly, but adding an element throws this error.

**Comment by mdwragg** [comment] 2016-05-27 21:30
Hi @trentgillham Can you post a gist or snippet of your code so I can see what is happening? Thanks!

Also, what browser is this happening in? What version of px-data-table is this also?

Thanks.

**Comment by kdinluks** [comment] 2016-06-03 18:03
@mdwragg we're facing the same issue. The problem is at the function _refreshInternalData.
It's going through the new dataset in the data variable and at some points referencing the old dataset in the _internalData variable.
And as _internalData has less records than data, the for loop breaks when it try's to access an index that doesn't exist in _internalData.
I've changed line 595 to 
`if(resetDataState || i >= this._internalData.length){`
And lines 605 - 607 to
`          _filtered: (resetDataState || i >= this._internalData.length ? false : this._internalData[i]._filtered),
          _selected: (resetDataState || i >= this._internalData.length ? false : this._internalData[i]._selected),
          _highlight: (resetDataState || i >= this._internalData.length ? {value:false, highlightColor: ''} : this._internalData[i]._highlight)`

Just adding a check for the _internalData size and the iteration variable.
I don't know what those variables are used for in the _internalData, so it would be good if you could check it and make the fix if possible.

**Comment by mdwragg** [comment] 2016-06-03 19:02
Hi @kdinluks - Can you provide a codepen/fiddle that shows the original issue, sadly I can't recreate it at all and really want to fix it!

This is a good starting point: https://codepen.io/mdwragg/pen/qNWrJQ

Thanks!

**Comment by kdinluks** [comment] 2016-06-07 20:23
@mdwragg take a look at this pen: http://codepen.io/kdinluks/pen/VjvXxw

Click the "First" button and it will load a dataset with 2 entries.
Click the "Second" button and you will see the error when we try to load 3 entries.
Click the "Third" and you will see it works with a smaller dataset.

Now if you try the "First" or "Second" it will not work because it has more data than the current dataset in the component.

**Comment by mdwragg** [comment] 2016-06-07 20:24
Awesome! Thanks so much for this. Will take a look @kdinluks ++

**Comment by mdwragg** [comment] 2016-06-10 21:43
@kdinluks - I was just about to take a look at this but the codepen doesn't work anymore :-(

Is it working for you? Not urgent - I can copy the code locally to recreate... Thanks!

**Comment by kdinluks** [comment] 2016-06-17 17:00
@mdwragg sorry I missed this comment. Codepen is not working for me as well. I guess it's something to do with your polygit import? Do you have another working codepen? I can replicate it again. Or if you are in SR I can show you in person.

**Comment by mdwragg** [comment] 2016-06-17 19:21
It's working for me again - it's the proxy authentication getting in the way of stuff again. Go to polygit website, sign in to the GE proxy page and all should work again hopefully...

Phew...

**Comment by kdinluks** [comment] 2016-06-17 21:33
@mdwragg oh this proxy. It's working for me as well. Please let me know if you can fix this issue. I've send a pull request with the fix if you want to take a look as well.

**Comment by mdwragg** [comment] 2016-10-12 23:31
This is now fixed. Yay!

**Closed by mdwragg** 2016-10-12 23:31 UTC
