### ISSUE TITLE
Column Chooser width issue

### ISSUE THREAD

**Issue by ArslanBouzid** [PredixDev/px-data-table#129] opened 2017-05-08 12:55 UTC
Hello,

There's a weird behavior that happens with the Column Chooser when the length of any column text is bigger than 5 letters.

At first, the column chooser appears correctly (width is OK) then, when I uncheck a column, its width gets stretched and doesn't go back to its initial value. Please check the uploaded image.

Regards,

Arslan

![image](https://cloud.githubusercontent.com/assets/7040747/25804930/e933ced6-33fd-11e7-9431-eef142ac8fcf.png)

**Comment by randyaskin** [comment] 2017-05-08 16:07
Duplicate of #125

**Closed by randyaskin** 2017-05-08 16:07 UTC
