### ISSUE TITLE
Unresolvable variable evt in _dataChanged function

### ISSUE THREAD

**Issue by simonovdenis** [PredixDev/px-data-table#91] opened 2016-12-27 17:15 UTC
In aha-table.html in _dataChanged function there's following code
`if(this._cellChanged(this._readContent(this._internalData[index], column), changeRec.value)){
          this._handleValidateEvent(evt);
        }`
Here there's variable evt, which is not defined before.

**Comment by randyaskin** [comment] 2017-01-09 23:59
duplicate of #77

**Closed by randyaskin** 2017-01-09 23:59 UTC
Labels: duplicate
