### ISSUE TITLE
Multiple Columns insplite of px-data-table-column

### ISSUE THREAD

**Issue by avn4986** [PredixDev/px-data-table#28] opened 2016-04-27 06:00 UTC
Hi, 
Following is the code  I have used to display 5 columns of HTML data but I am still getting 10 columns inspite of using <px-data-table-column> .

```
<px-data-table table-data="{{data}}">
	<px-data-table-column type="html" name="name" label="Well Name" filterable sortable></px-data-table-column>
	<px-data-table-column type="html" name="customerName" label="Customer Name" filterable sortable></px-data-table-column>
	<px-data-table-column type="html" name="productLine" label="Product Line" filterable sortable></px-data-table-column>
	<px-data-table-column type="html" name="wellID" label="Well ID" filterable sortable></px-data-table-column>
	<px-data-table-column type="html" name="regionCode" label="Region Code" filterable sortable></px-data-table-column>
 </px-data-table>
```

How do i go around to hide the other columns?

**Comment by mdwragg** [comment] 2016-04-27 06:08
Hi, can you provide a fiddle showing the issue? We've never seen that before...

You can use this as an example of how to create a fiddle using Px web components: https://jsfiddle.net/martinwragg/Lqmcwhw0/

Thanks!

**Comment by benoitjchevalier** [comment] 2016-05-04 21:15
@avn4986  I have finally been able to reproduce something similar,  I have delivered a fix in version 1.9.1, can you let me know if that fixes your issue?

**Comment by avn4986** [comment] 2016-05-05 16:55
I had duplicate columns. 
One showing hyperlink and one showing the whole statement as text. 
Also, I haven't tried to be version specific but I will definitely give it a try.

**Comment by 212402415** [comment] 2016-05-18 17:10
I still see the duplicate columns issue even with the latest version 1.9.5

**Comment by leahecole** [comment] 2016-08-12 18:18
Hi - I'm an internal GE user also seeing this issue. In my case, I had code very similar to avn4986's. When my data was coming from a json that lived outside of the file that had my px-data-table in it, I didn't have any issues, but when I made the json in the Polymer script at the end of the file, I got duplicates when using the px-data-table-column

**Comment by mdwragg** [comment] 2016-08-12 18:33
Hi @leahecole - we've haven't been able to recreate this at all sadly :-(

Can you please provide us a codepen/fiddle/jsbin that demonstrates the issue?

You can use this as a starting point: http://codepen.io/mdwragg/pen/ZOWvZP

Thanks in advance.

**Comment by leahecole** [comment] 2016-08-12 21:08
@mdwragg do you sit in San Ramon? I'm having issues duplicating it on codepen but if we're in the same office I'm happy to stop by

**Comment by mdwragg** [comment] 2016-08-12 21:46
I do sit in San Ramon. Seeing the error inside your app doesn't really help us fix and test it though. Can you create a larger repo that demonstrates the issue and link to it here? Thanks.

**Comment by 212402415** [comment] 2016-08-12 21:56
@mdwragg & @leahecole I had the similar issue when have the data available in the session and there is no backend call needed to get the data. I could fix this by putting the  timeout around the function which sets the table data.
$timeout (function () {
// initialize the data for the datatable
}, 50);

**Comment by avn4986** [comment] 2016-08-13 04:29
Sorry to jump in but timeout isn't a useful workaround because you've adjusted this according to your needs. What if somebody had more columns with larger data? I had to switch to jquery Datatables because of these issues. It is far more reliable plus to render your data you wouldn't have to use timeouts.

**Comment by 212402415** [comment] 2016-08-13 05:18
I agree timeout is not a proper fix for the issue. It is just a workaround to fix the duplicate column issue in our case. Since we wanted to use the px-data-table, we had to go with the workaround till the actual issue fixed at px-data-table side.

**Comment by leahecole** [comment] 2016-08-29 18:56
Hi @mdwragg I'm OOO in a different office this week but can try to do so next week

**Comment by mdwragg** [comment] 2016-10-12 23:32
Closing due to age and people aren't beating down our door to fix it...

**Closed by mdwragg** 2016-10-12 23:32 UTC

**Comment by mevillep** [comment] 2017-08-30 16:07
Hello, I am an internal GE user.  We are using 1.14.5, and the columns are duplicated when I use the same code as @avn4986. I tried upgrading to 3.0.0, still the same issue. 

any idea where or what the fix is, @mdwragg. Kindly help!!

**Comment by loopilla** [comment] 2018-03-21 08:44
Hello, I am a working for the GE as contractor and should use predix components. Honestly, This Predix has many problems, I can't belive that it is in production state. I understand it is a GE product, but almost useless in a real project.
Is there any fix for this px-data-table issue already?
