### ISSUE TITLE
Console error messages when px-data-table used as a bower-component

### ISSUE THREAD

**Issue by chinmainpadalkar** [PredixDev/px-data-table#121] opened 2017-04-21 17:50 UTC
# Submit an Issue

Hi,

We are using the px-data-table as a bower component in our application(version: 1.15.21). In our application, when I try to use one of the Print functionality, I see console error messages.
Attached is the screenshot of the error messages

## Screenshots (_optional, but very helpful_):
![consoleerror](https://cloud.githubusercontent.com/assets/11944935/25289786/132ba12c-2699-11e7-8f97-963c2f733cd9.PNG)

Please let me know if you need more information.

Thanks.

**Comment by randyaskin** [comment] 2017-04-21 22:35
Probably a duplicate of #93 which we still have not been able to reproduce

**Comment by chinmainpadalkar** [comment] 2017-04-24 18:05
Okay thank you for your quick response.

**Closed** 2017-04-24 18:36 UTC
