### ISSUE TITLE
px-data-table : Data is not filtered when copy/pasting a value in filter field.

### ISSUE THREAD

**Issue by fsevak** [PredixDev/px-data-table#89] opened 2016-12-27 13:40 UTC
Steps to replicate the issue : Copy any text for filtering. Paste in filter field using mouse

Expected: Data table should show filtered list

Actual:  Data is not filtered.

**Comment by mdwragg** [comment] 2016-12-30 20:56
Duplicate of #79

**Closed by mdwragg** 2016-12-30 20:56 UTC
