### ISSUE TITLE
Freeze header fields

### ISSUE THREAD

**Issue by kornfein** [PredixDev/px-data-table#87] opened 2016-12-15 13:17 UTC
We are using the px-data-table. The issue is that when the user scrolls the header scrolls out of view.  We would like to have the ability to freeze the header so it does not move during scrolling. This seems like it is what most users would want.

**Comment by mdwragg** [comment] 2016-12-16 01:19
This is a duplicate of https://github.com/PredixDev/px-data-table/issues/66 - Our friend @benmak11 is looking to implement this.

**Comment by mdwragg** [comment] 2016-12-16 01:20
Actually, I'll close this as this is represented well by the other discussion. Thanks for the enhancement request.

**Closed by mdwragg** 2016-12-16 01:20 UTC
Labels: enhancement
