### ISSUE TITLE
Need to bring a way to add child rows to parent rows are clicked.

### ISSUE THREAD

**Issue by aakashd24** [PredixDev/px-data-table#103] opened 2017-02-25 19:39 UTC
# Submit an Issue

Hi,

I Need to bring a way to add child rows when parent rows are clicked.Could you please suggest which part if i edited it may be possible soon
![table_enhancement](https://cloud.githubusercontent.com/assets/11085531/23334208/0f0c612a-fbc0-11e6-84f0-3503bb281e1f.PNG)

**Comment by randyaskin** [comment] 2017-02-27 17:16
Duplicate of #67

**Closed by randyaskin** 2017-02-27 17:16 UTC
Labels: duplicate, enhancement
