### ISSUE TITLE
Selected column header issue

### ISSUE THREAD

**Issue by Dhawal0693** [PredixDev/px-data-table#122] opened 2017-04-25 11:48 UTC
Hi,
I am facing a issue as mentioned in the attached docx. Please go through the docx as I have explained in detailed step with images.

Use Case :  
1.	Navigate through context browser till the last assest(px-context-browser)
2.	Now click on open button as seen in an above Image. After open is clicked there will be px-modal that contains px-data-table(selectable and single-select property is true)  (selected header is as Selected(0))
3.	Now select stage1 is selected  (Stage1 is highlighted and selected header is changed to Selected(1))
4.	Now I click on Ok and again navigate through context browser and select another asset and follow step 2 again
(Now when the user has clicked on the open button of another asset, I have cleared the table-data value and assign all-together new data then also the selected header is shown as Selected(1)  as seen below.

Expected Behaviour : Selected header should be reset or since it is single select there shouldn't be a number indicating how many items are selected.

Actual Behaviour : Selected header remains as Selected(1) even after table data is newly assigned
(I believe this is happening since only the table data is getting changed and the headers don't change when this happens so.)

[px-data-table issue docx.docx](https://github.com/PredixDev/px-data-table/files/954900/px-data-table.issue.docx.docx)

**Comment by randyaskin** [comment] 2017-04-25 17:25
Duplicate of #80 and #51 - see discussion and possible workaround there.

**Closed by randyaskin** 2017-04-25 17:25 UTC
